variables:
  GIT_STRATEGY: clone

stages:
  - deploy_app

deploy_app:
  stage: deploy_app
  script:
    - cd /var/www/bp-landing-art
    - sudo git reset --hard HEAD~1
    - sudo git pull
    - sudo npm i && sudo npm run build
    - sudo pm2 restart ecosystem.config.js
  tags:
    - main
