variables:
  GIT_STRATEGY: clone

stages:
  - deploy

deploy_app_dev:
  stage: deploy
  script:
    - cd /var/www/bp-landing-art
    - sudo git reset --hard HEAD~1
    - sudo git pull
    - sudo npm i && sudo npm run build
    - sudo pm2 restart ecosystem.config.js
  tags:
    - dev
  only:
    refs:
      - dev

deploy_app_prod:
  stage: deploy
  script:
    - cd /var/www/bp-landing-art-prod
    - sudo git pull
    - sudo npm i && sudo npm run build
    - sudo pm2 restart ecosystem.config.js
  tags:
    - main
  only:
    refs:
      - main
