variables:
  GIT_STRATEGY: clone
  # TELEGRAM_BOT_TOKEN: 1030266407:AAGfPZAaSZWhDavtbAOjJkB850W4rFxs78s
  # TELEGRAM_CHAT_ID: -430205717

stages:
  - deploy_app
  - success_jobs
  - failure_jobs

deploy_app:
  stage: deploy_app
  script:
    - cd /var/www/bp-landing-art
    - sudo git reset --hard HEAD~1
    - sudo git pull
    - sudo npm i && sudo npm run build
    - sudo pm2 restart ecosystem.config.js
  only:
    refs:
      - main

success_jobs:
  stage: success_jobs
  script:
    - echo "good"
    # - sh ./scripts/cicd-notification.sh ✅
  when: on_success
  only:
    refs:
      - main
failure_jobs:
  stage: failure_jobs
  script:
    - echo "bad"
    # - sh ./scripts/cicd-notification.sh ❌
  when: on_failure
  only:
    refs:
      - main
